{
 "title": "◾️ BBxPing",
 "description": "[v2] brand-new design woohoo!",
 "tags": [
  "SLOMO",
  "Blackbox Exporter",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "SRC",
    "query": {
     "query": "label_values(probe_success,job)"
    }
   },
   {
    "name": "code",
    "query": {
     "query": "label_values(probe_success{job=\"$job\"},code)"
    }
   },
   {
    "name": "source_city",
    "query": {
     "query": "query_result(0 < avg_over_time(probe_duration_seconds{job=\"$job\", city!=\"\", ip=\"$ip\"}[1d]) < 0.005)"
    }
   },
   {
    "name": "local_machine",
    "query": {
     "query": "query_result(bottomk(1, 0 < avg_over_time(probe_duration_seconds{job=\"$job\", code!=\"ANYCAST\", ip=\"$ip\"}[1d]) < 0.003))"
    }
   },
   {
    "name": "city",
    "label": "DST1",
    "query": {
     "query": "label_values(probe_success{job=\"$job\"},city)"
    }
   },
   {
    "name": "city2",
    "label": "DST2",
    "query": {
     "query": "label_values(probe_success{job=\"$job\"},city)"
    }
   },
   {
    "name": "isp",
    "label": "SVC",
    "query": {
     "query": "label_values(probe_success{job=\"$job\"},isp)"
    }
   },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(probe_success{job=\"$job\"},ip)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "OVERVIEW",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "description": "<p>This dashboard is created by <strong>@SLOMO</strong> / <a href=\"https://github.com/TPCTPCTPC/Grafana-Dashboards\" target=\"_blank\">TPCTPCTPC@GitHub</a></p>",
     "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
     "options": {
      "content": "<h5><strong>◾️ BBxPING Gen2</strong> <sup>$ip</sup></h5>\n<div style=\"background: linear-gradient(to right, rgba(255, 255, 255, 0), #4564a3);\">\n  <p style=\"font-size: 13px;\"><strong>🔖 &nbsp;SRC | ${job}</strong></p>\n</div>"
     }
    },
    {
     "type": "geomap",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "clamp_max(avg(probe_duration_seconds{job=\"$job\",ip=\"$ip\"}) by (code,city), 1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "geomap",
     "gridPos": { "h": 5, "w": 4, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "clamp_max(avg(probe_duration_seconds{job=\"$job\",ip=\"$ip\"}) by (code,city), 1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "geomap",
     "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "clamp_max(avg(probe_duration_seconds{job=\"$job\",ip=\"$ip\"}) by (code,city), 1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(0 < probe_duration_seconds{job=\"$job\",domestic=\"true\",ip=\"$ip\"} < 1)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(avg(0 < probe_duration_seconds{job=\"$job\",code!=\"ANYCAST\",city!=\"$source_city\",ip=\"$ip\"} < 1) by (city))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(0 < probe_duration_seconds{job=\"$job\",code=\"ANYCAST\",ip=\"$ip\"} < 1)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(0 < probe_duration_seconds{job=\"$job\",isp=\"$isp\",ip=\"$ip\"} < 1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count by (instance) (probe_success))",
       "legendFormat": "__auto"
      },
      {
       "expr": "count(count by (city) (up{job=\"$job\", code!=\"ANYCAST\", city!=\"\"} == 1))",
       "legendFormat": "__auto"
      },
      {
       "expr": "count(count by (isp) (up{job=\"$job\", isp!=\"\"} == 1))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DESTINATION",
     "type": "table",
     "gridPos": { "h": 11, "w": 5, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(0 < probe_duration_seconds{job=\"$job\",city!=\"\",ip=\"$ip\"} < 1) by (city)",
       "legendFormat": "{{city}}"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 1, "w": 14, "x": 5, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "0 < probe_duration_seconds{job=\"$job\",code=\"ANYCAST\",ip=\"$ip\"} < 1",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "TARGET / GROUP",
     "type": "table",
     "gridPos": { "h": 11, "w": 5, "x": 19, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "0 < avg by (name) (probe_duration_seconds{job=\"$job\",ip=\"$ip\"} < 1)",
       "legendFormat": "{{city}}"
      }
     ]
    },
    {
     "type": "geomap",
     "gridPos": { "h": 10, "w": 14, "x": 5, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "clamp_max(avg(probe_duration_seconds{job=\"$job\",ip=\"$ip\"}) by (code,city), 1)",
       "legendFormat": "__auto"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(0 < probe_duration_seconds{job=\"$job\",city=\"$city\",ip=\"$ip\"} < 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(0 < probe_duration_seconds{job=\"$job\",city=\"$city2\",ip=\"$ip\"} < 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "COMPARE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "RTT | $city2",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "0 < probe_duration_seconds{job=\"$job\",city=\"$city2\",ip=\"$ip\"} < 1",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "clamp_max(probe_duration_seconds{job=\"$job\",city=\"$city2\",ip=\"$ip\"}, 1)",
       "legendFormat": "__auto"
      },
      {
       "expr": "(1 - avg by (name) (avg_over_time(probe_success{job=\"$job\",city=\"$city2\",ip=\"$ip\"}[1m]))) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "RTT | $city",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "0 < probe_duration_seconds{job=\"$job\",city=\"$city\",ip=\"$ip\"} < 1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RTT | $isp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "0 < probe_duration_seconds{job=\"$job\",isp=\"$isp\",ip=\"$ip\"} < 1",
     "legendFormat": "{{name}} | {{code}}"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "clamp_max(avg(probe_duration_seconds{job=\"$job\",isp=\"$isp\",ip=\"$ip\"}) by (code,city), 1)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(clamp_max(avg(probe_duration_seconds{job=\"$job\",isp=\"$isp\",ip=\"$ip\"}) by (code,city), 1))",
     "legendFormat": "{{city}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(0 < probe_duration_seconds{job=\"$job\",isp=\"$isp\",ip=\"$ip\"} < 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PLR | $city",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg_over_time(probe_success{job=\"$job\",city=\"$city\",ip=\"$ip\"}[$__interval])) * 100",
     "legendFormat": "{{code}} | {{name}}"
    },
    {
     "expr": "avg((1 - avg_over_time(probe_success{job=\"$job\",city=\"$city\",ip=\"$ip\"}[$__interval]))) * 100",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "PLR | World",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg by (city) (avg_over_time(probe_success{job=\"$job\",name!=\"$local_machine\",code!=\"ANYCAST\",ip=\"$ip\"}[$__range]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(avg_over_time(probe_success{job=\"$job\", name!=\"$local_machine\", ip=\"$ip\"}[1h]))) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - avg(avg_over_time(probe_success{job=\"$job\", name!=\"$local_machine\", ip=\"$ip\"}[1d]))) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - avg(avg_over_time(probe_success{job=\"$job\", name!=\"$local_machine\", ip=\"$ip\"}[1w]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "clamp_max(probe_duration_seconds{job=\"$job\",city=\"$city\",ip=\"$ip\"}, 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - avg by (name) (avg_over_time(probe_success{job=\"$job\",city=\"$city\",ip=\"$ip\"}[1m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(avg_over_time(probe_success{job=\"$job\", name!=\"$local_machine\", ip=\"$ip\"}[$__interval]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}