{
 "title": "Node Information",
 "tags": [
  "Prometheus",
  "Node Exporter",
  "SLOMO"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  {
   "title": "Instance Overview",
   "type": "table",
   "description": "Customised by @SLOMO",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "((1 - (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) by (instance)) ^ 1.3) ^ (1/3) * 0.5 + \n( 1 - (1 - avg(node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) by (instance)) ^ 6) ^ (1/3) * 0.3 + \n(1 - max(rate(node_disk_io_time_seconds_total[$__rate_interval]))by (instance) ^ 1.1) ^ (1/2) * 0.2) * 100",
     "legendFormat": "__auto"
    },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "__auto" },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes))) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) by (instance)) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(node_filesystem_avail_bytes{fstype=~\"ext.?|xfs\"}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(irate(node_network_receive_bytes_total{device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*)\"}[$__rate_interval]) * 8) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(irate(node_network_transmit_bytes_total{device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*)\"}[$__rate_interval]) * 8) by (instance)",
     "legendFormat": "__auto"
    },
    { "expr": "node_netstat_Tcp_CurrEstab - 0", "legendFormat": "__auto" },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Traffic Usage (Approx.)",
   "type": "timeseries",
   "description": "Mostly accurate within the range of 12 hours.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{instance=~\".*\", device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*)\"}[30s])) * 15",
     "legendFormat": "Upload"
    },
    {
     "expr": "sum(irate(node_network_receive_bytes_total{instance=~\".*\", device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*)\"}[30s])) * 15",
     "legendFormat": "Download"
    },
    {
     "expr": "sum(irate(node_network_receive_bytes_total{instance=~\".*\"}[30s])) * 15 + sum(irate(node_network_transmit_bytes_total{instance=~\".*\"}[30s])) * 15",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "^ ^",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"$job\"})",
     "legendFormat": "Active Instances"
    },
    {
     "expr": "sum(node_netstat_Tcp_CurrEstab)",
     "legendFormat": "All Connections"
    },
    {
     "expr": "(sum(irate(node_network_receive_bytes_total{device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*)\"}[$__rate_interval]) + irate(node_network_transmit_bytes_total{device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*)\"}[$__rate_interval]))) * 8",
     "legendFormat": "Total Throughput"
    }
   ]
  },
  {
   "title": "Aggregate System Load [5m]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_load5", "legendFormat": "{{instance}}" },
    { "expr": "1", "legendFormat": "baseline" }
   ]
  },
  {
   "title": "Average Speed Distribution",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*)\"}[$__rate_interval]) * 8 + irate(node_network_receive_bytes_total{device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*)\"}[$__rate_interval]) * 8",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*)\"}[$__rate_interval]) * 8",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Overall Established & TIME_WAIT Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_netstat_Tcp_CurrEstab)",
     "legendFormat": "Current Established"
    },
    { "expr": "sum(node_sockstat_TCP_tw)", "legendFormat": "TIME_WAIT" }
   ]
  },
  {
   "title": "Instance Resource Details - $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average System Load",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_load1{instance=\"$node\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "node_load5{instance=\"$node\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "node_load15{instance=\"$node\"}",
       "legendFormat": "15m"
      },
      {
       "expr": "count(node_cpu_seconds_total{instance=\"$node\", mode='system'}) by (instance)",
       "legendFormat": "CPU Cores"
      }
     ]
    },
    {
     "title": "Disk Space Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=\"$node\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"$node\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "RAM Cache + Buffer"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
       "legendFormat": "SWAP Used"
      }
     ]
    },
    {
     "title": "CPU Activity Analysis",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
       "legendFormat": "Busy System"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
       "legendFormat": "Busy User"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=~\".*irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
       "legendFormat": "Busy IRQs"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",  mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
       "legendFormat": "Busy Other"
      }
     ]
    },
    {
     "title": "Partition Status",
     "type": "table",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=\"$node\", fstype=~\"ext.*|xfs|nfs\", mountpoint !~\".*pod.*\"} - 0",
       "legendFormat": "__auto"
      },
      {
       "expr": "node_filesystem_avail_bytes {instance=\"$node\", fstype=~\"ext.*|xfs|nfs\", mountpoint !~\".*pod.*\"} - 0",
       "legendFormat": "__auto"
      },
      {
       "expr": "(node_filesystem_size_bytes{instance=\"$node\", fstype=~\"ext.*|xfs|nfs\", mountpoint !~\".*pod.*\"} \n- node_filesystem_free_bytes{instance=\"$node\", fstype=~\"ext.*|xfs|nfs\", mountpoint !~\".*pod.*\"})\n* 100 / node_filesystem_size_bytes{instance=\"$node\", fstype=~\"ext.*|xfs|nfs\", mountpoint !~\".*pod.*\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Read/Write Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{device}}_read"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{device}}_write"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(time() - node_boot_time_seconds{instance=\"$node\"})",
       "legendFormat": "⏱️ Uptime"
      },
      {
       "expr": "count(node_cpu_seconds_total{instance=\"$node\", mode='system'})",
       "legendFormat": "💎 Core(s)"
      },
      {
       "expr": "max(node_filesystem_size_bytes{instance=\"$node\",fstype=~\"ext.?|xfs\"})",
       "legendFormat": "💾 Disk Size"
      },
      {
       "expr": "sum(node_memory_MemTotal_bytes{instance=\"$node\"})",
       "legendFormat": "🫙 Memory Total"
      }
     ]
    },
    {
     "title": "Network Socket",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=\"$node\"}",
       "legendFormat": "CurrEstab"
      },
      {
       "expr": "irate(node_netstat_Tcp_RetransSegs{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Tcp_RetransSegs"
      },
      {
       "expr": "node_sockstat_sockets_used{instance=\"$node\"}",
       "legendFormat": "sockets_used"
      },
      {
       "expr": "irate(node_netstat_Tcp_InSegs{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Tcp_InSegs"
      },
      {
       "expr": "irate(node_netstat_Tcp_OutSegs{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Tcp_OutSegs"
      },
      {
       "expr": "node_sockstat_TCP_tw{instance=\"$node\"}",
       "legendFormat": "TCP_tw"
      },
      {
       "expr": "irate(node_netstat_TcpExt_ListenDrops{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "TcpExt_ListenDrops"
      },
      {
       "expr": "node_sockstat_UDP_inuse{instance=\"$node\"}",
       "legendFormat": "UDP_inuse"
      }
     ]
    },
    {
     "title": "Network Bandwidth Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=\"$node\"}[$__rate_interval]) * 8",
       "legendFormat": "recv {{device}}"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=\"$node\"}[$__rate_interval]) * 8",
       "legendFormat": "trans {{device}} "
      }
     ]
    }
   ]
  }
 ]
}